{
  self,
  config,
  lib,
  hostname,
  cfg,
  ...
}: let
  inherit (self.sops.env) common-file trusted-file host-file;
  inherit (self.sops.text) twofa-file;
  inherit (lib) mkEnableOption mkOption types;

  has-age-recipient = cfg.age-recipient != null;

  # ---- environment variable files ----
  # The whole KEY=VALUE file of each applicable scope is materialized as data
  # and parsed by zsh at startup. No per-key registry is needed: adding a
  # variable is a change to secrets/<scope>/env alone.
  env-data-dir = "${config.xdg.configHome}/sops-nix/env";
  env-loader-path = "${config.xdg.configHome}/sops-nix/env-loader.zsh";

  # A generated helper that exports the materialized data files. Keeping the
  # loop here keeps the shell init to a single `source`: the values are
  # assigned as single arguments and are never re-parsed, so arbitrary
  # characters (spaces, $, quotes, backticks) stay literal.
  env-loader-text = ''
    # Generated by home-manager: export the materialized sops env data files.
    () {
      local file line name value
      for file in "${env-data-dir}"/common "${env-data-dir}"/trusted "${env-data-dir}"/host; do
        [[ -r $file ]] || continue
        while IFS= read -r line; do
          [[ -z $line || $line == \#* ]] && continue
          name=''${line%%=*}
          [[ $name =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
          value=''${line#*=}
          export "$name=$value"
        done < "$file"
      done
    }
  '';

  mk-env-file = scope: file: {
    name = "env-file/${scope}";
    value = {
      sopsFile = file;
      key = "";
      format = "dotenv";
      path = "${env-data-dir}/${scope}";
      mode = "0600";
    };
  };

  env-files =
    lib.optionals (has-age-recipient && builtins.pathExists common-file) [
      (mk-env-file "common" common-file)
    ]
    ++ lib.optionals (has-age-recipient && cfg.trusted && builtins.pathExists trusted-file) [
      (mk-env-file "trusted" trusted-file)
    ]
    ++ lib.optionals (has-age-recipient && builtins.pathExists (host-file hostname)) [
      (mk-env-file "host" (host-file hostname))
    ];

  # ---- whole-file (or keyed) secret files ----
  scope-dir = scope:
    if scope == "host"
    then self.sops.dirs.host hostname
    else self.sops.dirs.${scope};

  declared-files = lib.filterAttrs (_: file: file.enable) config.my.secrets.files;

  file-secrets =
    lib.mapAttrsToList (
      name: file: {
        name = "file/${name}";
        value =
          {
            sopsFile = "${scope-dir file.scope}/${file.file}";
            key = file.key;
            format = file.format;
          }
          // lib.optionalAttrs (file.path != null) {
            path = file.path;
            mode = file.mode;
          };
      }
    )
    declared-files;

  # ---- 2FA files ----
  declared-twofa = lib.filterAttrs (_: account: account.enable) config.my.secrets.twofa;

  mkAccountSecret = name: field: file-name: {
    name = "2fa/${name}/${file-name}";
    value = {
      sopsFile = twofa-file;
      key = "${name}/${field}";
      format = "json";
      path = "${config.xdg.configHome}/2fa/${name}/${file-name}";
      mode = "0600";
    };
  };

  twofa-secrets = lib.concatLists (lib.mapAttrsToList (
      name: account:
        [(mkAccountSecret name "key" "key")]
        ++ lib.optionals account.recoveryCodes [
          (mkAccountSecret name "recovery_codes" "recovery-codes")
        ]
    )
    declared-twofa);

  all-secrets = env-files ++ file-secrets ++ twofa-secrets;
in {
  options.my.secrets = {
    files = mkOption {
      type = types.attrsOf (types.submodule {
        options = {
          enable = mkOption {
            type = types.bool;
            default = true;
            description = "Whether to materialize this secret file.";
          };

          scope = mkOption {
            type = types.enum ["common" "trusted" "host"];
            default = "host";
            description = "Access scope of the sops file backing this secret.";
          };

          file = mkOption {
            type = types.str;
            description = "File name inside the scope directory under secrets/.";
          };

          key = mkOption {
            type = types.str;
            default = "";
            description = "Key in the sops file; an empty string materializes the whole file.";
          };

          format = mkOption {
            type = types.enum ["yaml" "json" "binary" "ini" "dotenv"];
            default = "yaml";
            description = "Format of the sops file.";
          };

          path = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "Path the decrypted content is materialized to; placeholder-only when null.";
          };

          mode = mkOption {
            type = types.str;
            default = "0600";
            description = "Permissions of the materialized file.";
          };
        };
      });
      default = {};
      description = "Registry of sops-backed files materialized to the home directory.";
    };

    twofa = mkOption {
      type = types.attrsOf (types.submodule ({name, ...}: {
        options = {
          enable = mkEnableOption "2FA files for ${name}";

          recoveryCodes = mkOption {
            type = types.bool;
            default = false;
            description = "Whether recovery codes are stored for this account.";
          };
        };
      }));
      default = {};
      description = ''
        Registry of 2FA secrets. Each entry is backed by the trusted sops file
        secrets/trusted/2fa.json:

        ```json
        {
          "github": {
            "key": "JBSWY3DPEHPK3PXP",
            "recovery_codes": "1234-5678\n9012-3456"
          }
        }
        ```

        and is materialized to
        {file}`~/.config/2fa/<name>/key` and, when enabled,
        {file}`~/.config/2fa/<name>/recovery-codes`, both mode 0600.
      '';
    };
  };

  config = {
    sops = {
      age.sshKeyPaths = ["${config.home.homeDirectory}/.ssh/id_ed25519"];

      secrets = builtins.listToAttrs all-secrets;
    };

    home.file."${env-loader-path}" = lib.mkIf (env-files != []) {
      text = env-loader-text;
    };

    programs.zsh.initContent = lib.mkIf (env-files != []) (lib.mkBefore ''
      if [[ -r "${env-loader-path}" ]]; then
        source "${env-loader-path}"
      fi
    '');
  };
}
